> # Football Data Analysis
This dataset functions as a seasonal player-performance aggregation table, designed to track individual player statistics across different competitions and teams.
   - **Kaggle Dataset Link** -https://www.kaggle.com/datasets/xfkzujqjvx97n/football-datasets

> ### Data Columns Descriptions

**Core Identifiers & Metadata**
 - player_id: The unique identifier for the individual player.
 - season_name: The specific football season being recorded (e.g., "2025/2026").

- competition_id: The unique identifier for the specific tournament or league.

- competition_name: The human-readable name of the competition (e.g., "English Premier League", "UEFA Champions League").

- team_id: The unique identifier for the club or national team the player - represented during these matches.

- team_name: The name of the team (e.g., "Real Madrid", "Arsenal").

**Squad Selection & Participation**
- nb_in_group: Number in Group/Squad. The total number of matchday squads the player was named to (i.e., either started or sat on the bench).

- nb_on_pitch: Number on Pitch. The total number of matches where the player actually stepped onto the field (Starts + Subbed in).

- subed_in: Subbed In. The number of times the player started the match on the bench but was brought on as a substitute.

- subed_out: Subbed Out. The number of times the player started the match but was taken off before the final whistle.

- minutes_played: The total cumulative duration (in minutes) the player spent on the pitch during the specified season and competition.

**Attacking & Goal Scoring Metrics**
- goals: The total number of goals scored by the player. Note: This usually includes open-play goals, headers, free-kicks, and penalties.

- assists: The number of goal assists credited to the player (the final pass leading directly to a goal).

- penalty_goals: The subset of the player's total goals that were scored directly from penalty kicks. (Crucial for calculating "non-penalty goals").

- own_goals: The number of times the player accidentally scored against their own team.

**Discipline Metrics**
- yellow_cards: The total number of single yellow cards received across the matches.

- second_yellow_cards: The number of times the player received a second yellow card in a single match, resulting in an indirect red card.

- direct_red_cards: The number of times the player was shown a straight red card for a severe foul, misconduct, or denying an obvious goal-scoring opportunity.

**Defensive & Goalkeeping Metrics**
- **Note**: While these columns exist for all players, they are primary KPIs for Goalkeepers and Defenders).

- goals_conceded: The total number of goals let in by the team while this specific player was on the pitch.

- clean_sheets: The number of full matches where the team did not concede a single goal while the player was participating.

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv("player_performances.csv")
df.head(1)

,player_id,season_name,competition_id,competition_name,team_id,team_name,nb_in_group,nb_on_pitch,goals,assists,own_goals,subed_in,subed_out,yellow_cards,second_yellow_cards,direct_red_cards,penalty_goals,minutes_played,goals_conceded,clean_sheets
0,1,08/09,OBLG,NOFV-Oberliga Süd,4825,FC Eilenburg,9,9,0.0,0,0,0,2,0,0,1,0,NaN,0,0

> # About This DataSet

- **Row** : 1878719
- **Columns** : 20
   - int   14
   - object  4
   - float 2

In [10]:
df.columns.to_list()

['player_id',
 'season_name',
 'competition_id',
 'competition_name',
 'team_id',
 'team_name',
 'nb_in_group',
 'nb_on_pitch',
 'goals',
 'assists',
 'own_goals',
 'subed_in',
 'subed_out',
 'yellow_cards',
 'second_yellow_cards',
 'direct_red_cards',
 'penalty_goals',
 'minutes_played',
 'goals_conceded',
 'clean_sheets']

In [11]:
df.shape

(1878719, 20)

In [12]:
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1878719 entries, 0 to 1878718
Data columns (total 20 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   player_id            1878719 non-null  int64
 1   season_name          1878719 non-null  object
 2   competition_id       1878719 non-null  object
 3   competition_name     1878719 non-null  object
 4   team_id              1878719 non-null  int64
 5   team_name            1878719 non-null  object
 6   nb_in_group          1878719 non-null  int64
 7   nb_on_pitch          1878719 non-null  int64
 8   goals                1740517 non-null  float64
 9   assists              1878719 non-null  int64
 10  own_goals            1878719 non-null  int64
 11  subed_in             1878719 non-null  int64
 12  subed_out            1878719 non-null  int64
 13  yellow_cards         1878719 non-null  int64
 14  second_yellow_cards  1878719 non-null  int64
 15  direct_red_cards     1878719 non-null  int64
 16  penalty_goals        1878719 non-null  int64
 17  minutes_played       708161 non-null   float64
 18  goals_conceded       1878719 non-null  int64
 19  clean_sheets         1878719 non-null  int64
dtypes: float64(2), int64(14), object(4)
memory usage: 286.7+ MB

In [16]:
df.dtypes.value_counts()

int64      14
object      4
float64     2
Name: count, dtype: int64

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
player_id,1878719.0,291629.480617,292207.879140,1.0,55494.0,189482.0,447768.0,1453181.0
team_id,1878719.0,10692.977300,17703.140043,1.0,798.0,3060.0,11449.0,134550.0
nb_in_group,1878719.0,9.929085,10.843456,1.0,2.0,4.0,16.0,51.0
nb_on_pitch,1878719.0,8.156783,9.865284,0.0,1.0,3.0,13.0,51.0
goals,1740517.0,0.952719,2.283932,0.0,0.0,0.0,1.0,50.0
assists,1878719.0,0.446945,1.247370,0.0,0.0,0.0,0.0,29.0
own_goals,1878719.0,0.015329,0.130054,0.0,0.0,0.0,0.0,9.0
subed_in,1878719.0,1.673163,3.035122,0.0,0.0,0.0,2.0,38.0
subed_out,1878719.0,1.855993,3.260543,0.0,0.0,1.0,2.0,40.0
yellow_cards,1878719.0,1.111522,1.919704,0.0,0.0,0.0,1.0,21.0
second_yellow_cards,1878719.0,0.033941,0.193069,0.0,0.0,0.0,0.0,5.0
direct_red_cards,1878719.0,0.035137,0.194554,0.0,0.0,0.0,0.0,4.0
penalty_goals,1878719.0,0.075515,0.441409,0.0,0.0,0.0,0.0,14.0
minutes_played,708161.0,606.181230,681.591337,1.0,178.0,337.0,758.0,4590.0
goals_conceded,1878719.0,0.801500,4.606050,-1.0,0.0,0.0,0.0,111.0
clean_sheets,1878719.0,0.191107,1.204661,0.0,0.0,0.0,0.0,29.0

In [18]:
df.describe(include=['object'])

       season_name competition_id competition_name   team_name
count      1878719        1878719          1878719     1878719
unique         102           1643             1988       15411
top          22/23            FAC           FA Cup  Arsenal FC
freq        106476          40958            40958        4063